# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by build_config.py. Do not edit manually.
datas = [
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\templates', 'templates'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\static', 'static'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\website', 'website'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\security', 'security'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\blocklists', 'blocklists'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\utils', 'utils')
]
binaries = []
hiddenimports = ['flask', 'flask.sessions', 'flask_cors', 'flask_limiter', 'flask_wtf', 'werkzeug', 'requests', 'psutil', 'ssl', 'dotenv', 'cryptography', 'cryptography.fernet', 'cryptography.hazmat', 'cryptography.hazmat.primitives', 'cryptography.hazmat.backends', 'cryptography.x509', 'bcrypt', 'pyotp', 'security.yara_scanner', 'security.ml_yara_analyzer', 'security.c2_detector', 'security.secure_memory', 'security.local_assistant', 'security.assistant_trainer', 'security.assistant_database', 'security.local_agent', 'quarantine_utils', 'file_crypto', 'utils.paths', 'waitress', 'sklearn', 'sklearn.ensemble', 'sklearn.linear_model', 'sklearn.svm', 'sklearn.tree', 'sklearn.neural_network', 'sklearn.preprocessing', 'sklearn.decomposition', 'sklearn.pipeline', 'sklearn.metrics', 'sklearn.model_selection', 'numpy', 'scipy', 'scipy.sparse', 'onnxruntime', 'yara', 'joblib', 'pefile', 'tlsh', 'lief']
excludes = ['tensorflow', 'torch', 'torchvision', 'sentence_transformers', 'transformers', 'safetensors', 'matplotlib', 'IPython', 'ipykernel', 'notebook', 'pytest', 'pydantic', 'pydantic_core', '_pyinstaller_hooks_contrib', 'Crypto']

a = Analysis(
    [r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\app.py'],
    pathex=[r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\pyinstaller_hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name='antivirus_server',
    debug=False, bootloader_ignore_signals=False, strip=False,
    upx=True, upx_exclude=[], runtime_tmpdir=None,
    console=True, disable_windowed_traceback=False, argv_emulation=False,
    target_arch=None, codesign_identity=None, entitlements_file=None,
)
coll = COLLECT(
    exe, a.binaries, a.datas, strip=False, upx=True, upx_exclude=[], name='antivirus_server',
)
