# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by buildconfig.py — do not edit manually.
import os

datas = [
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\templates', 'templates'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\static', 'static'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\website', 'website'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\security', 'security'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\blocklists', 'blocklists'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\utils', 'utils'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\.env', '.'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\.env.server', '.'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\cloud\\.env', 'cloud'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\cloud\\cert.pem', 'cloud'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\cloud\\key.pem', 'cloud'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\cloud\\localhost.crt', 'cloud'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\cloud\\localhost.key', 'cloud'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\malware_signatures.json', '.'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\malware_signatures.txt', '.')
]
binaries = []
hiddenimports = ['flask', 'flask.sessions', 'flask_cors', 'flask_limiter', 'flask_wtf', 'werkzeug', 'werkzeug.middleware', 'werkzeug.middleware.proxy_fix', 'requests', 'psutil', 'ssl', 'dnslib', 'dns.resolver', 'dotenv', 'cryptography', 'cryptography.fernet', 'bcrypt', 'pyotp', 'stripe', 'stripe.error', 'stripe.webhook', 'stripe.checkout', 'stripe.Product', 'security.yara_scanner', 'security.c2_detector', 'security.secure_memory', 'security.local_assistant', 'security.assistant_trainer', 'security.assistant_database', 'security.local_agent', 'quarantine_utils', 'file_crypto', 'utils.paths', 'waitress', 'json', 'hashlib', 'secrets', 'webbrowser']
excludes = ['tensorflow', 'torch', 'torchvision', 'sklearn', 'scipy', 'numpy', 'onnxruntime', 'lightgbm', 'lief', 'pyssdeep', 'yara', 'tlsh', 'pefile', 'matplotlib', 'pandas', 'IPython', 'ipykernel', 'notebook', 'pytest']

a = Analysis(
    [r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\cloud\cloud_server.py'],
    pathex=[r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, a.binaries, a.datas, [],
    name='cloud_server',
    debug=False, bootloader_ignore_signals=False, strip=False,
    upx=True, upx_exclude=[], runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False, argv_emulation=False,
    target_arch=None, codesign_identity=None, entitlements_file=None,
    icon=[r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\static\favicon.ico'],
)
