# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by buildconfig.py — do not edit manually.
import os

datas = [
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\templates', 'templates'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\static', 'static'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\website', 'website'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\security', 'security'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\blocklists', 'blocklists'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\utils', 'utils'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\cloud\\cert.pem', 'cloud'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\cloud\\localhost.crt', 'cloud'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\malware_signatures.json', '.'),
    ('C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\\malware_signatures.txt', '.'),
    # ML models — all model files except assistant.gguf (1.6 GB, disabled in cloud mode)
]

# Add entire models directory except assistant.gguf (disabled in cloud mode, saves 1.6 GB)
_models_dir = r'C:\Users\bpier\OneDrive\Documents\antivirus-yara-rules-c\antivirus-yara-rules-c\models'
if os.path.isdir(_models_dir):
    for _f in os.listdir(_models_dir):
        _fp = os.path.join(_models_dir, _f)
        if os.path.isfile(_fp) and _f != 'assistant.gguf':
            datas.append((_fp, 'models'))
binaries = []
hiddenimports = ['flask', 'flask.sessions', 'flask_cors', 'flask_limiter', 'flask_wtf', 'werkzeug', 'werkzeug.middleware', 'werkzeug.middleware.proxy_fix', 'requests', 'psutil', 'ssl', 'dnslib', 'dns.resolver', 'dotenv', 'cryptography', 'cryptography.fernet', 'bcrypt', 'pyotp', 'security.yara_scanner', 'security.c2_detector', 'security.secure_memory', 'security.local_assistant', 'security.assistant_trainer', 'security.assistant_database', 'security.local_agent', 'quarantine_utils', 'file_crypto', 'utils.paths', 'waitress', 'json', 'hashlib', 'secrets', 'webbrowser', 'sklearn', 'sklearn.ensemble', 'sklearn.linear_model', 'sklearn.svm', 'sklearn.tree', 'sklearn.neural_network', 'sklearn.preprocessing', 'sklearn.decomposition', 'sklearn.pipeline', 'sklearn.metrics', 'sklearn.model_selection', 'numpy', 'scipy', 'scipy.sparse', 'onnxruntime', 'yara', 'joblib', 'pickle', 'pandas', 'pefile', 'tlsh', 'lief']
excludes = ['tensorflow', 'torch', 'torchvision', 'matplotlib', 'IPython', 'ipykernel', 'notebook', 'pytest']

a = Analysis(
    [r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\cloud\cloud_server.py'],
    pathex=[r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, a.binaries, a.datas, [],
    name='cloud_server',
    debug=False, bootloader_ignore_signals=False, strip=False,
    upx=True, upx_exclude=[], runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False, argv_emulation=False,
    target_arch=None, codesign_identity=None, entitlements_file=None,
    icon=[r'C:\\Users\\bpier\\OneDrive\\Documents\\antivirus-yara-rules-c\\antivirus-yara-rules-c\static\favicon.ico'],
)
