server {
    listen 80;
    server_name isolation-bytes.com www.isolation-bytes.com;

    client_max_body_size 500M;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    location /static/ {
        alias /opt/antivirus-server/static/;
        expires 30d;
    }

    location /download/ {
        alias /opt/antivirus-server/cloud/downloads/;
        autoindex on;
        expires 1h;
    }
}

server {
    listen 443 ssl;
    server_name isolation-bytes.com www.isolation-bytes.com;

    ssl_certificate /opt/antivirus-server/cloud/cert.pem;
    ssl_certificate_key /opt/antivirus-server/cloud/key.pem;

    client_max_body_size 500M;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    location /static/ {
        alias /opt/antivirus-server/static/;
        expires 30d;
    }

    location /download/ {
        alias /opt/antivirus-server/cloud/downloads/;
        autoindex on;
        expires 1h;
    }
}
